### ISSUE TITLE
an error in running a command line version

### ISSUE THREAD

**Issue by wisekh6** [MariaNattestad/Assemblytics#1]
Dear Maria,

To use a command line version of your Assemblytics, I ran the following script, but it failed.
Would you resolve it? 

Thank you,

HK 

```
[hkim6@cnode280 test]$ sh ../Assemblytics test.nucmer.delta test 10000 /Assemblytics/default
Input delta file: test.nucmer.delta
Output prefix: test
Unique anchor length: 10000
Path to R scripts: /scratch/bcb/hkim6/IACS2Verhaak/pipeline/Assemblytics/default
1. Filter delta file
../Assemblytics: line 82: syntax error near unexpected token `('
../Assemblytics: line 82: `                cat <(echo -e $HEADER) $OUTPUT_PREFIX.variants_within_alignments.bed $OUTPUT_PREFIX.variants_between_alignments.be

```

**Comment by MariaNattestad** [comment]
Don't use sh, but instead just make Assemblytics executable and then run it exactly like in the README:
chmod +x Assemblytics
Assemblytics delta_file output_prefix unique_anchor_length path_to_R_scripts
So for your example that would be:
../Assemblytics test.nucmer.delta test 10000 /Assemblytics/default
