### ISSUE TITLE
Assemblytics requires R(ggplot2) and X11 ?

### ISSUE THREAD

**Issue by lufuhao** [MariaNattestad/Assemblytics#11]
Assemblytics requires R(ggplot2) and X11 ?

I got error on Linux server: 
..........
4. Combine variants between and within alignments
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  : 
  unable to start device PNG
Calls: png
In addition: Warning message:
In png(paste(output_prefix, ".Assemblytics.size_distributions.",  :
  unable to open connection to X11 display ''
Execution halted
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  : 
  unable to start device PNG
Calls: png
In addition: Warning message:
In png(file = paste(plot.output.filename, ".png", sep = ""), width = 1000,  :
  unable to open connection to X11 display ''
Execution halted
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  : 
  unable to start device PNG
Calls: png
In addition: Warning message:
In png(file = paste(prefix, ".Assemblytics.Nchart.png", sep = ""),  :
  unable to open connection to X11 display ''
Execution halted

**Comment by MariaNattestad** [comment]
You can use Assemblytics on the web at assemblytics.com, which requires no
installation.
