### ISSUE TITLE
input assembly stats from assemblytics

### ISSUE THREAD

**Issue by chunlinxiao** [MariaNattestad/Assemblytics#13]
Just wondering - In the assembly stats output file, for the "Query", are the "Number of sequences" and "Total sequence length" representing the stats from the input assembly with length filtering,  or from unfiltered original assembly?

**Comment by MariaNattestad** [comment]
Thanks for the question. Those assembly statistics are based on the whole input delta file, before any unique anchor filtering that Assemblytics applies.
