### ISSUE TITLE
Output variant sequences

### ISSUE THREAD

**Issue by CWYuan08** [MariaNattestad/Assemblytics#14]
Hi Maria,
I am wondering whether it is possible to get the variant sequences, so that I can compare them to variants called by a different software. 

Thank you very much 
Ulrika

**Comment by MariaNattestad** [comment]
Hi Ulrika

Unfortunately the input file that Assemblytics takes (a delta file) doesn't include the sequences so Assemblytics can't do this automatically for you.
However, there is a great way to do it by using the output bed file from Assemblytics and running it against your fasta file using bedtools fastaFromBed: https://bioweb.pasteur.fr/docs/modules/bedtools/2.17.0/content/fastafromBed.html

Hope that helps!
Maria
