### ISSUE TITLE
script for modifying  a genome with known SVs

### ISSUE THREAD

**Issue by liufy11** [MariaNattestad/Assemblytics#19]
Hi Zev !
there're different pipelines to detect SV , I don't know which one to choose . Can you offer me the script to  created a modified version of the human genome with simulated insertions and deletions embedded at known positions as mentioned in your article ? I'm  a novice in bioinformation  thanks for your help!

**Comment by MariaNattestad** [comment]
Who's Zev?
I would only recommend using Assemblytics if you have an assembly and want to call variants from that, which is common for people who work in plants/animals and want to compare their de novo assembly to another species or other existing reference genome. If you are not sure this applies to you, it usually means you should choose a regular alignment-based variant-calling approach. Something like Lumpy if you have Illumina data or look into PBSV or Sniffles if you have long-read data such as from PacBio or Oxford Nanopore.
Best of luck!
