### ISSUE TITLE
assemblytics uses python 2

### ISSUE THREAD

**Issue by 0xaf1f** [MariaNattestad/Assemblytics#20]
Python 2 has been on its way out for a while and is finally scheduled to die in January. The python scripts need to be updated to work with Python 3.

**Comment by MariaNattestad** [comment]
Sorry for the delay in answering this. I've been meaning to update Assemblytics in a couple of ways, and I'm just starting to work on this now. Please stay tuned.

**Comment by MariaNattestad** [comment]
This is now done as part of the version 1.1 release. Notably, it maintains compatibility with python 2 as well.
