### ISSUE TITLE
Assembly statistics mismatch

### ISSUE THREAD

**Issue by cssulliv** [MariaNattestad/Assemblytics#29]
Hi,

I am trying to look at structural variants between 2 highly similar genomes that are composed of 7 scaffolds each. I ran these in mummer using the -l 100 -c 500  --maxmatch flags to generate the delta file, which I uploaded into assemblytics. When I viewed the Assembly Statistics it shows that one of my genomes only had 6 scaffolds. 

I am not entirely sure how to resolve the observed mismatch and wanted to know if other people have experienced something similar? 

I have attached a copy of the delta file used as a .zip and a screen shot of the assembly statistic page. 

[nucmer_run1v2.delta.zip](https://github.com/MariaNattestad/Assemblytics/files/4411199/nucmer_run1v2.delta.zip)
<img width="282" alt="Assembly Stat Mismatch" src="https://user-images.githubusercontent.com/41393799/78067582-af032780-7332-11ea-82b3-6406563c53c9.png">

**Comment by MariaNattestad** [comment]
Those metrics should include everything in the delta file. Have you tried
looking to see if the 7th scaffold is in the delta file? If not, try
smaller values for -c and -l.
Let me know if that helps!

**Comment by cssulliv** [comment]
Hi Maria,

This is the information in the delta file. It seems that using the -l 100 and -c 500 removed the second scaffold. I am happy to try different parameters but would like to know if there is a particular parameter cutoff required to generate a delta file that would still be appropriate/compatible to use in assemblytics? 

Thank you for the help and just wanted to say that I love the web interface of the program. 

```
NUCMER
>JdFR_1362B_NitroMAG_7_000000000006 JdFR_1362A_NitroMAG_3_000000000003 284158 153901
1 153901 1 153901 19 19 0
0
>JdFR_1362B_NitroMAG_7_000000000001 JdFR_1362A_NitroMAG_3_000000000004 27978 27978
1 27978 27978 1 19 19 0
0
>JdFR_1362B_NitroMAG_7_000000000005 JdFR_1362A_NitroMAG_3_000000000005 106031 106031
1 106031 1 106031 0 0 0
0
>JdFR_1362B_NitroMAG_7_000000000003 JdFR_1362A_NitroMAG_3_000000000006 159322 159322
1 159322 159322 1 0 0 0
0
>JdFR_1362B_NitroMAG_7_000000000007 JdFR_1362A_NitroMAG_3_000000000002 338117 338151
1 338117 1 338117 0 0 0
0
>JdFR_1362B_NitroMAG_7_000000000006 JdFR_1362A_NitroMAG_3_000000000007 284158 129884
154275 284158 1 129884 0 0 0
0
>JdFR_1362B_NitroMAG_7_000000000004 JdFR_1362A_NitroMAG_3_000000000001 481113 480957
1 59258 480957 421701 26 26 0
41918
0
59413 481113 421701 1 0 0 0
0
```

**Comment by MariaNattestad** [comment]
Excellent. Any parameters would be appropriate. The higher numbers are
mostly to help it run faster and prevent tons of tiny alignments, which is
more of an issue on larger genomes. So feel free to play with the
parameters.
Thanks for appreciating the web app!
