### ISSUE TITLE
Unauthenticated File upload Vulnerability

### ISSUE THREAD

**Issue by ghost** [MariaNattestad/Assemblytics#33]
Attackers can upload malicius files
https://github.com/MariaNattestad/Assemblytics/blob/58fb52567b402ab54bc8c4f1126ac1565d46f61f/public/file_upload.php#L7

**Comment by MariaNattestad** [comment]
Thanks for bringing this up. The uploaded files are not executed, so I'm not sure what the attack would consist of, but I would be happy to take a pull request if you have a fix for this issue. Thanks!
