### ISSUE TITLE
 Output bed file has no chromosomes in the first column

### ISSUE THREAD

**Issue by lxxiaoxiaLi** [MariaNattestad/Assemblytics#35]
Hi Maria,
thanks for this wonderful tool.  I find the output bed file I generate (I'm running Assemblytics） has no chromosomes in the first column , but When I let my sample.delta files upload to the website(http://assemblytics.com/), the output bed file has chromosomes in the first column, So I want to why? How should I solve this problem?
#reference      ref_start       ref_stop        ID      size    strand  type    ref_gap_size    query_gap_size  query_coordinates       method
        3011968 3012034 Assemblytics_w_1        66      +       Deletion        66      0       :139517-139517:+        within_alignment
        3183128 3183182 Assemblytics_w_2        54      +       Deletion        54      0       :310092-310092:+        within_alignment
        3209069 3209153 Assemblytics_w_3        84      +       Deletion        84      0       :335922-335922:+        within_alignment
        3644058 3644058 Assemblytics_w_5        55      +       Insertion       0       55      :750072-750127:+        within_alignment
        3837286 3837286 Assemblytics_w_6        78      +       Insertion       0       78      :942419-942497:+        within_alignment
        4264770 4264825 Assemblytics_w_7        55      +       Deletion        55      0       :1368592-1368592:+      within_alignment
        4673304 4673387 Assemblytics_w_8        83      +       Deletion        83      0       :1728231-1728231:+      within_alignment
        4968463 4968463 Assemblytics_w_9        69      +       Insertion       0       69      :1940538-1940607:+      within_alignment
        5364412 5364472 Assemblytics_w_10       60      +       Deletion        60      0       :2334363-2334363:+      within_alignment
        5546544 5546544 Assemblytics_w_11       78      +       Insertion       0       78      :2500330-2500408:+      within_alignment

Best Regards,
Xiaoxia Li

**Comment by MariaNattestad** [comment]
Can you share the first several lines of your delta file? The
chromosome/contig names come from the headers in the delta file.

**Comment by lxxiaoxiaLi** [comment]
delta file as below:
NH002.fa NH001.fa
NUCMER
>Chr9 ctg1 23012720 17943667
2873122 2981468 1893 109489 1307 1307 0
18
1
14
25
1
1
6
1
13
2
9
1
-37
-1
-1
-1
-1
-1
-1
-1
-1
-2
175
135
1
1
1
1
2
1
1
5
2
68
10
4
5
1
1
4
8
4
10
4
30
7
4
-145
-1
-1
-1
-1
-1
-1
-1
-1
-2
146
1
1
4
1
1
1
1
1
90
12
3
9
1
1
-9
23
1
1
1
1
5
1
1
1
3
15
1
1
12
5
1
6
19
9
12
-9
41
1
1
194
1
5
4
5
8
6
14
5
2
19
11
16
6
11
1
150
12
1
6
1
30
1
1
3
2
1
5
2
5
15
19
1
5
21

**Comment by MariaNattestad** [comment]
Thanks for bringing this to my attention! I was able to reproduce the error and fix it. See https://github.com/MariaNattestad/Assemblytics/commit/3db55120e7f45c8fbbf14bf0f26186682c465689. If you use version 1.2.1 it should work.
Thank you!
