### ISSUE TITLE
What does diagonal red lines/dots mean in interactive plot?

### ISSUE THREAD

**Issue by MehmetGoktay** [MariaNattestad/Assemblytics#36]
Hi Maria,

I have a hard time to interpret these red lines on interactive plot of Assemblytics.

Could you please tell me what does red dots/lines mean?

Best Regards,
Mehmet
![ss](https://user-images.githubusercontent.com/8544565/88932694-b73a8780-d27e-11ea-95bd-8f3bc4a6a034.png)

**Comment by MariaNattestad** [comment]
Black is forward alignment, red is reverse.

**Comment by MariaNattestad** [comment]
Black is unique alignments, red is repetitive. It means the red alignments are the ones filtered out during the unique anchor filtering step in Assemblytics and are not used to call variants. See the paper for more details on unique anchor filtering.
