### ISSUE TITLE
Failed file upload - Is the Assemblytics server down?

### ISSUE THREAD

**Issue by Neato-Nick** [MariaNattestad/Assemblytics#37]
Any time I upload a delta file, I get the error message "No file uploaded."

I was worried some weird alignments in my .delta file could've caused this, so I downloaded the sample delta file, ran that with default settings, and I still got the same error.

Here's my screen, after waiting a couple seconds for the sample delta file to upload.
![image](https://user-images.githubusercontent.com/5849554/102026925-b9950e00-3d55-11eb-81aa-2f5ffa0aa6c8.png)

**Comment by Neato-Nick** [comment]
Reading other issues, the upload folder may be full again?

https://github.com/MariaNattestad/Assemblytics/issues/7

**Comment by MariaNattestad** [comment]
Thanks for the heads up. I don't have access to that server anymore, so I asked Mike who still does. We'll get back to you when it's (hopefully easily) fixed.

**Comment by mschatz** [comment]
Yes, please try again. The server that hosts the application was full.

Good luck!

Mike

**Comment by Neato-Nick** [comment]
Awesome, file uploads are working again :)

The web server is great, and the CLI was pretty easy to pick up in the mean time. Thanks all!

**Comment by mschatz** [comment]
Thanks for the note!

**Comment by emmannaemeka** [comment]
Hey! I am having similar problem. Saying No file upload. Can you help?

**Comment by mschatz** [comment]
Please try again! The server filled up which prevented any one from
uploading, but I cleared out a few hundred GB of older results.

Thanks!
Mike

**Comment by nishita-kalepalli** [comment]
Hi! I've been trying to upload files but I'm encountering the same issue. Is the web server filled up?

**Comment by MariaNattestad** [comment]
Sorry about that! It might take longer to fix this time, unfortunately -- we're having permissions issues on the server. It might take a while, so I recommend you run it locally or try another variant caller in the meantime.

**Comment by mschatz** [comment]
Thanks for letting me know. The server had filled, but I was able to clean
up some space so things are working again.

Good luck!

Mike

**Comment by AAFREENSAKINA** [comment]
Hi, 
I am encountering similar problems. I am actively working on Assemblytics and encounter such problems often. Can you please help?

**Comment by mschatz** [comment]
Please try again - the server filled up but I cleaned out a lot of space

Good luck!

Mike
