### ISSUE TITLE
R and Python versions

### ISSUE THREAD

**Issue by shabirmoosa** [MariaNattestad/Assemblytics#40]
Hi,

Could you please provide the versions of R and python used and of the below dependency packages

R
ggplot2
plyr
RColorBrewer
scales

Python
argparse
numpy

I see an error while running the pipeline and looks like it is coming from the plyr package. Also I'm facing  a problem with rendering the plots on the web app installed locally 

Thanks
Shabir

**Comment by MariaNattestad** [comment]
Ah yes I've seen issues with R packages for my tutorial videos where code that used to work is not compatible with future versions. I think in Python it's better, once you get to python 3 of course.

Here are the R packages I have installed on my system, which I believe are the ones I had installed last time I ran Assemblytics locally:
R: 3.4.0
plyr: 1.8.6
ggplot2: 2.2.1
RColorBrewer: 1.1.2
scales: 1.1.1

Also for Python:
Python: 3.7.6
numpy: 1.18.1
argparse: 1.1

Hope that helps!
Maria
