### ISSUE TITLE
Variants with the same coordinates

### ISSUE THREAD

**Issue by kyleLesack** [MariaNattestad/Assemblytics#41]
Hi,

First of all, thank you for this great tool! I have been using it to compare some assembled _C. elegans_ strains against the _C. elegans_ reference. 

I have noticed that some of my bed files contain entries with identical coordinates. For example:

`grep "Assemblytics_b_2020" mydata.Assemblytics_structural_variants.bed`
II      14564319        14564430        Assemblytics_b_2020     111     +       Deletion        111     0       tig00000041:264546-264546:+     between_alignments
`grep "Assemblytics_b_2057" mydata.Assemblytics_structural_variants.bed`
II      14564319        14564430        Assemblytics_b_2057     111     +       Deletion        111     0       tig00000044:11348-11348:+       between_alignments

I assume that this has something to do with my assemblies and the alignment data used to call the variants for them as the query_coordinates differ. I could see how a large duplicated segment in a genome assembly could contain the same deletion. However, I wouldn't want it to be counted twice, as that could bias variant counts.

Is this something that you are aware of? Am I correct that this is an artifact that could be collapsed into a single deletion?

**Comment by MariaNattestad** [comment]
Yes each contig in the assembly is treated separately and Assemblytics
doesn’t do any deduplication, so that is something to be aware of if your
contigs might have duplicates.

**Comment by kyleLesack** [comment]
Thanks for the quick response. That makes sense. 

BTW - these calls can be flagged pretty easily using the bedtools cluster command in case anyone has a similar concern.
