### ISSUE TITLE
Bed file coordinate system

### ISSUE THREAD

**Issue by agolicz** [MariaNattestad/Assemblytics#42]
Hi,
I have started using Assemblytics lately and I am trying to understand the .bed file coordinates.
Are they the standard 0-based half open?

Agnieszka

**Comment by MariaNattestad** [comment]
I think so, but it’s been a long time, so I’m not sure. I recommend
checking it, e.g. by looking at one of the smaller examples, which should
also help you see what it’s doing.

**Comment by agolicz** [comment]
Thanks. That's where my question comes from. I checked a couple of examples and it looked like it is 1-based, which is more gff/vcf than bed style.
