### ISSUE TITLE
Issue with coordinates of variants 

### ISSUE THREAD

**Issue by MartuGio** [MariaNattestad/Assemblytics#44]
Hello, thanks for the great tool and for your support.

I have aligned 2 (not scaffolded) assemblies of Phaseolus vulgaris (about 500 Mb) with minimap2 using this command:
minimap2 --MD -L -2 -ax asm5 -f 0.005 -t 10 -I 4G -K 500M -o <output> <reference.fasta> <query.fasta> 

The alignment file (in sam format) was converted in delta format using a script available at: https://github.com/malonge/RaGOO/blob/master/sam2delta.py

I have used both the online version of Assemblytics and the 1.2.1 version available at https://github.com/MariaNattestad/Assemblytics, using 10,000, 100,000 and 50 as unique sequence length, maximum and minimum variant size respectively. 

By visualizing the alignment (resulting from minimap2) with IGV visualizer, I have noticed that sometimes, especially in variants called within the alignment, the coordinates of the variants called by Assemblytics do not correspond.
Here below an example of incongruences between coordinates: 

<img width="818" alt="example" src="https://user-images.githubusercontent.com/99256707/152978318-d644976a-7363-47ea-a6d3-f27bf6a1ead1.png">

Do you have an explanation for these incongruences? 

Thanks for your help,

Giovanni

**Comment by MariaNattestad** [comment]
Hi Giovanni

Have you tried other scripts for converting sam to delta?
Assemblytics calls variants largely by simply parsing the delta file, which I verified extensively with MUMmer show-aligns to see that they were producing the same results, so I'm surprised you saw this problem.
Do you have other ways of verifying that the sam2delta.py script is accurate? I'm guessing the IGV screenshot above is showing the sam file, but maybe there are ways of visualizing the delta file itself to ensure that it matches what is in the sam file?

Maria
