### ISSUE TITLE
Tandem_contraction empty when long unqie_anchor_length choosen

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [MariaNattestad/Assemblytics#5]
The Tandem_contraction is empty when I chose unquie_anchor_length 50kbp compared to 10kbp. 

Any reason?

http://qb.cshl.edu/assemblytics/analysis.php?code=SUIBTG2OcqVoxxqb6eKK
http://qb.cshl.edu/assemblytics/analysis.php?code=vDHlfEIeWnTDLyhn3eVn

**Comment by MariaNattestad** [comment]
The 4 tandem contractions you had at 10kbp were likely in alignments that were anchored in less than 50kbp unique sequence, so when you increased the level to 50kbp those alignments got filtered out and the variants in them were no longer called.

**Comment by BenjaminSchwessinger** [comment]
Thanks this makes sense.
