### ISSUE TITLE
Coordinates in the negative strand are not correct

### ISSUE THREAD

**Issue by wjwei-handsome** [MariaNattestad/Assemblytics#50]
Hi Maria:
Assemblytics is great tool for SV calling. But I meet some problem about coordinates in negative strands:
Firstly, I generated a multi-alignment-file between two genomes. And I convert maf-format to delta-format using[ my sript](https://github.com/wjwei-handsome/scripts/blob/main/maf-convert.py).

It is noteworthy that, there is a negative-postive-strand alignment:

![image](https://user-images.githubusercontent.com/56633839/202638650-1a40c3ca-db2b-47cf-94ff-02fe9030af8f.png)

Finally, I get the result from Assemblytics. But the **insertion sequence**  is NOT correct according to the **query_coordinates** in result bed file.  The **actual** coordinate position should be :

>Coord_A =  Alignment_End - (Coord_W - Alignment_Start)
>Coord_A == Coord_Actual; Coord_W == Coord_Wrong

Just like this:
![C4A84F55BFFE758B8AA809C2151FAFEF](https://user-images.githubusercontent.com/56633839/202640604-a8126814-2fb0-47c9-a54e-163ae1c4f99b.jpg)

PS: Sorry for my ugly simple stroke.

And I revised [Assemblytics_within_alignment.py](https://github.com/wjwei-handsome/Assemblytics/blob/wwj-fix-query_coord/scripts/Assemblytics_within_alignment.py), add the judgement about strand, the result seem to be correct for me.

**Comment by MariaNattestad** [comment]
Can you reproduce this problem with a delta file that comes from MUMmer?
For example, it’s not clear if this is only happening because your script
created a weird delta file that might be incorrect. And can you show the
problem using any viz tools in MUMmer? Again just trying to eliminate the
potential sources of the error before proceeding. Thanks!
