### ISSUE TITLE
Stuck on "Checking progress"

### ISSUE THREAD

**Issue by bmansfeld** [MariaNattestad/Assemblytics#53]
Hey folks,
Still love this tool for SVs! 
Seems like something is up on the server side as even loading the example data shows
`"Checking progress..." `
and stalls there.
Trying to load up some of my old results from a link but that doesn't work either.
Happy new year!
Ben

**Comment by mschatz** [comment]
Thanks for your interest! I fixed the links for the examples. Can you try
again with your new samples? Unfortunately I had to purge some old results
to make space on the server

Happy New Year

Mike
