### ISSUE TITLE
Error encountered when running Assemblytics locally

### ISSUE THREAD

**Issue by yjx1217** [MariaNattestad/Assemblytics#6]
Hi Maria,

I ran Assemblytics locally on the computing server of our institute and got the error below. The same input delta file ran smoothly via the online version of Assemblytics. Do you know what might caused this issue? The ggplot warining issue seems easy to fix but I cannot figure out what causes the error related with "as_tibble". Thanks in advance!

Input delta file: input.delta
Output prefix: input.delta.filtered
Unique anchor length: 10000
Path to R scripts: .
input.delta.filtered
STARTING,DONE,Starting unique anchor filtering.
1. Filter delta file
Keeping fully unique alignments even if they are below the unique anchor length of 10000 bp
Use --unique-length X to set the unique anchor length requirement. Default is 10000, such that each alignment must have at least 10000 bp from the query that are not included in any other alignments.
header:
/home/jxyue/Projects/Recombination/ParentGenomeAln_Mummer-Assemblytics/DBVPG6044.genome_with_mt.relabeled/DBVPG6044_chrI.fa /home/jxyue/Projects/Recombination/ParentGenomeAln_Mummer-Assemblytics/YPS128.genome_with_mt.relabeled/YPS128_chrI.fa
NUCMER
First read through the file: 0 seconds for 0 query-reference combinations
Filtering alignments of 1 queries
Progress: 100%
Progress: 100%
Deciding which alignments to keep: 0 seconds for 1 queries
Reading file and recording all the entries we decided to keep: 0 seconds for 745 total lines in file
UNIQFILTER,DONE,Step 1: Assemblytics_uniq_anchor.py completed successfully. Now finding variants between alignments.
2. Finding variants between alignments
Loaded 9 alignments
BETWEEN,DONE,Step 2: Assemblytics_between_alignments.pl completed successfully. Now finding variants within alignments.
3. Finding variants within alignments
WITHIN,DONE,Step 3: Assemblytics_within_alignment.py completed successfully. Now combining the two sets of variants together.
4. Combine variants between and within alignments
COMBINE,DONE,Step 4: Variants combined successfully. Now generating figures and summary statistics.
The following `from` values were not present in `x`: Repeat_expansion, Tandem_contraction
Error: 'as_tibble' is not an exported object from 'namespace:tibble'
In addition: Warning message:
`geom_bar()` no longer has a `binwidth` parameter. Please use `geom_histogram()` instead. 
Execution halted
null device 
          1 
SUMMARY,DONE,Step 5: Assemblytics_summary.py completed successfully

Best,
Jia-Xing

**Comment by MariaNattestad** [comment]
Hi Jia-Xing

I haven't seen that error before, but it looks to me like some internal code in facet_grid in ggplot2 that either has a bug or a compatibility issue with some dependency or other package that is interfering with its namespace. 

This looks like the same problem on StackOverflow:
[http://stackoverflow.com/questions/41553484/error-using-ggplot2-facet-grid-as-tibble-not-an-expected-object-from-namespa](http://stackoverflow.com/questions/41553484/error-using-ggplot2-facet-grid-as-tibble-not-an-expected-object-from-namespa)

Are you also using the ggplot2 2.2.0 version?
It looks like it includes some changes to facet_grid, which may have something to do with this:
[https://github.com/tidyverse/ggplot2/releases](url) 

Best,
Maria

**Comment by yjx1217** [comment]
Hi Maria,

Thanks for the reply. It makes sense. My current ggplot version is "ggplot2 2.2.1".

Best,
Jia-Xing
