### ISSUE TITLE
delta files problem

### ISSUE THREAD

**Issue by Gon1976** [MariaNattestad/Assemblytics#60]
Open new issue.

I dont really make changes to the output of nucmer. I run as assemblytics webpage indicates:
nucmer --maxmatch -l 100 -c 500 TcDm25_H1.fasta Dm28c_v4.fasta  -p Dm28vsH1
and upload without changes to assemblytics. Do you think could be a problem with my fasta files or my nucmer installation?

Your answer was:
"I'm guessing you tried to change the file programmatically and accidentally added some newlines where they shouldn't be. When you fix this, please take a close look at your file in a text editor and also try running it through the MUMmer tool suite first before reporting problems in Assemblytics, since it will be faster for you to check that these files are valid using e.g. MUMmer's "show-aligns" or "coords" commands. Once those are working and it looks okay , then you can try Assemblytics again. Good luck!"

**Comment by MariaNattestad** [comment]
Did the show-aligns and coords commands work?

**Comment by Gon1976** [comment]
I dont understand how works
show-aligns deltafile refID qyID (refID and qyID refers to chromosomes names? )

**Comment by MariaNattestad** [comment]
Check the MUMmer documentation for that one.
