### ISSUE TITLE
The case where the sequence strand of SV is a reverse strand

### ISSUE THREAD

**Issue by jwli-code** [MariaNattestad/Assemblytics#61]
I used Assemblytics and Syri software to process the nucmer results respectively, and found that reverse strand SV would occur in Assemblytics. Later, I extracted the sequence and compared the difference between the two sequences at the same site, and found some problems.
For this kind of problem, what should I do in the case of reverse chains? Which should be right ?
The following are the original output results of the two software and the results of my extraction sequence.
syri_result
`C09     62451491        DEL26880        TCACAATACTAAAAGCCCTATATGCTGAGATTATAGGCTGCCACGTCACCCAAAATAATCAACCAATAAAAAACAGTTAATCGGACATGTCAGACAGGCCTCCTGTGTTAGTTTCGTCCAGAGTCGAGCATCTGACAATGTGGGCTTCATCCGATAAATTTTCCACTTGGGCTTTGTCTGTTTTTTATATGCGCGGTTGGCCACATAATATATGAATCACCACATTATTTTATGTCAACGTAATTTATGAATCACATTACCTTATGGCAATCTTAATTTATTGAGAATACCTTTCCTCTTCCTTCAAAATGTCGATAGACCTTTGCCCTTTCTCTCACAACTCAAGACTTTTGCCAAGGTGAACAAAGAGAATTCGAGAGACTTGCAAAGTTGCAATGCGCCAGAGCGATGGCGATCGTCGCGTCGAAACGGATTGGTTTCCCCTGCGGCCCCATCCATGTTCTCGCCGATCAATCATTTCCAACTCTCGCTATCAACTCTTTTACCGTCTCCGGCAACGTAAGTTAAATCTCATGTTTCGTTTTCTTTCACTTCTTTTGAAGCTTTTCGTTTGTTTGGTGTTGTTGCAGAGTGAGTGCTCCGAGGTATCAGATCATTCCATTAGGGACAGATCTTAATTGGCTTCTTTTGCTGACTGATTTTCAAGAAAGTTTTTATACATGGCCACCGTGAAGCCTAGGATCATTGGAGGTATGTTCTTTCTCCGTTTCCAATCTTACGATTGTATGCCACTAATAATATTGAAGAATGAACCATTTTGTTAATAATCTTTTATTTATAATTTTTTAAGGTGTGACATGGGTGTGGTGTTTCTCACTTGACAGATATATGTAAAGATCGAATAGGAAGAAATATCAAGCACTTTCTGTCTCGGGTTTAGTGGACTAGGTGATTGCGCCAATTGACATTCTTAAGAAAATAAATGAGATAACCTTACACCAAATCCCTAGGCTTCAATCCATGGCAGGTTCATCGTGTTGGAGAGATTCATTCGTCTTGGTATTCCATGTTTTTTCTTTTAACGCCACTCAGATTTCAGGATCTCCTATCTAACTATTATCGGGTTTTATTTCAGGTCGTGGAGCATGTTTTTGTTCATTTGCCGTTCACTAAGAAATAAGTAGTCACTCCAACAGGTACGAGAGGAGTATGTCTGAGCATTGACATAGTTTATGCAGTTTCTTAGATGCCATGCAGAGTAGTGGAGTTAGCTTATTCAGTTGGTTATAATTTGTTATCTTTTCCAAACCAGGAGCTGTGTATACCGGATTTGATTTTTGCAAGAAACTTTGTGGGTTTCTCAATGATTCGAAGGTGAGGTTTGAAAATACTTTGGCTTAATTTTTTTTTCTCCCACCTATAGTACTCTTGGAAGAGTATATTATTTAGAGAAATTCTCTATAGTTTTTGTCACAAATATAGCCTTTAAGGATCAAAATGACCAAAATATTGTATTAAAGGATGTGTTTTTGGGTTTATGGTTTAGAATTTAGGGTTTAAAGTTTATGATTTAGGGTTTAGAGTTAACGGATGAGGTTTTGGGGGTATGATTTCAAATTTTAAAAACTTAAAAAATATTAAAATTTTCAAAATAAAAAAAAATTATTTTGGTCATTTTATTTTTTTAAGTCTATTTTTGTGACACAAAACTTTAAAAAATCTATTTGAGAGAATTGTCTTATTATTTATGGTTATAAGGTGTGTATGCTTTGTTAGTAGTGAAAGTATAAAGCTTATTGAAAAAATCCTTCCAAATTAGCTTTACCATTATTCTGTCTGTCTTTTTCTTAAATTACATTAATGAACTTTCTGATTTATGGGTCTTGATCATTTGTGTATAAAAATTACTCGTGTGTAATACATATATATATTCTTTCAGGATTCCCTGCTTAAAGTTTTTGAAGTATATGTTTCACAGAAGAAATCAACTTTCTTTTTCAGTGACAATGTGAAAGTGGAATGCTTCTCCGTCACCTATTTCTTCTCTGAAAAACACATCCCCTAGCTCTGCCTTCACGCAAACTTTGTCGTCTCCCGCCGTCCACAATGCTTTCTTTCTCCTCAGTTTCTCTCATTTTGAAGTTCATATGATCACCTAGGTATTAACTTATAAGTATTTGATTGATTAAGATAATTATTCAAGTATTTTTTGCCCATTGTTTATAATCCTTAACAACCAGCATCTATATTGGTCAGTTCAGGTTAAGATAGCTACATTTCACTGTTTAGGATAAGGTTGGATGATCTTTCTGAAGATACTAATGTCTATCATCGGATCTAAAACTCAAAGAAACTTAACATCTTTCTTGATGCTCTTAACAGGGAATCCTCTTTTCCCCGGGAAAAATATAGTCCATCAATTGGATATGATGAATGATCTGTTGGGAACTCCATTTGTGAAACTATTGGAAGGGTCAGTGTCCCTTACCTCTCTCCACAATGCTTACAACAACTGCATTGTTACTTTTCTTGGCTGAACTGCTTTCACTGAATGTGACAGGTGAGGAACGAGAAAGCTGGAAGATACTTGAGGAGCATGAGGTTGAAGAAGTCTATTCGTTTTTCACATAAGCTTCCACATGACGATCCTCTCGATCTTCGTATTCTACAAAAGTTGTTGTCTTTTGAGCTCAATGAACGGCCTACATTTGAAGAGGTGCTTCACAAAATTATTTTACTACATTCCTTATGATCTATTTGGTTGTATTCAACTAAAATTATTGTTTAGGGGTTAGTCCTGACACTTGTGGAGTACTTCAAGGGTGTAGCTAAGAAAGAGACTATATATGAGCTCTCAAAGAGATCCCTCTGTTCAACCTGTCACCAAGCTGGAATTCGAGTTTGAGAGGCTGAAGATCACAAAAGAGGCCATGCCAGAGCTCATATATAGTATCTTGAGACTGCTCTTGAGTACCACCCAAAGATGCTAAAAGAATACTTGGATTTGTGGAATAGAAGATTTTGCTTCATATTAAGTTTTTTTTGTCAAAATTAATATTAATATTAAGTTTTTTGCAGAAGAGAAAAACAAACGTACTACAGTGTTTCTATTACCGGCACTACCCAACAAAAAACATGCTCGAGTTGGTGGTCGGAAGATGAAAGATTTAGGTTTATGAAGAATATGCTTTTTAATGAAGAATATGTTTTCTGTTGCAACATTTAGTTTACACCAAAATAAACAATAGCTTATAAAAATAACTAAATACATAATTTTGTTTTTGGTAGTAGGCAAGTAGCTAGAAAGGAAGTCAGAGAAATGGGACTATGAGTTCATGTCAATAGGTTGTTGTGGTTAGAAGACCATACTCAATCGAAACTTTACATGATTTTGAAATAAATCATTTCACTAATTTTCTCGAAACAATAATGTTATCTCTTGGCAGCTCCATATGATTTCAGCCATTAACTTTGATCTCTTCAGTGTTCTGAGACAATATTACGAACACAGAAAAACAAATTAACGAATATATGAAATCCGTGTTCTTGAGATAATATTAGGAACACAAAAACAAATTAATGAATATAAGAAACCCATTGAATATTAATCTAAAATCAATTCAATCATAACAATTTGCAATGACTGTATATACTTCATAACCTGAAAATTAAATTACGTTAATTGATTTAAATTTCAAACTCTATAAAGTAACTCAAATTCCCAAAATTAGAGACCTCTTTTATTAGTCATCAAAAAGATTCCACCAGTCCCATCTTAAACATTCAATAGGCCAATATTTAAACTAACATAAGAAAGAGATTTTCAAACAAAAACGGCAAATTTATTGCCACAAATTACTCTGAATATATTTAAAATCACAAATAATTAAATTTGTTTATTAAATAAAACCTATACTCAATATAAAAATGAAGATAGTGGTAAAAATTAAAGAGAAACTAAAAGAACATAAAGCAACATATGAAAAACTGCATTTAATAGTTGTATTAATTCCTTAAAAAATGTTGAAGAAAATTAATAAATACACTTAATATCTATCAAAAATATACACTCTCTAAAATTAACTACAGAGAAAACACAAAAATAATCATAGTTTATGTACATATGGAAATTCTGCAATATTCTATAATTAAATAACAAAACTAATTGTAAAATTTTAAAAGCAATAATCCGCGCGAAGCGCGGAAAACGAT      T       .       PASS    END=62455663;ChrB=C09;StartB=59463369;EndB=59463369;Parent=SYN10402;VarType=ShV;DupType=.
`
Assemblytics_result
`C09     62451491        62455664        Assemblytics_b_27075    4177    +       Deletion        4173    -4      C09:59463365-59463369:- between_alignments`

two software sequence
`C09     62451491        Assemblytics_b_27075    TCACAATACTAAAAGCCCTATATGCTGAGATTATAGGCTGCCACGTCACCCAAAATAATCAACCAATAAAAAACAGTTAATCGGACATGTCAGACAGGCCTCCTGTGTTAGTTTCGTCCAGAGTCGAGCATCTGACAATGTGGGCTTCATCCGATAAATTTTCCACTTGGGCTTTGTCTGTTTTTTATATGCGCGGTTGGCCACATAATATATGAATCACCACATTATTTTATGTCAACGTAATTTATGAATCACATTACCTTATGGCAATCTTAATTTATTGAGAATACCTTTCCTCTTCCTTCAAAATGTCGATAGACCTTTGCCCTTTCTCTCACAACTCAAGACTTTTGCCAAGGTGAACAAAGAGAATTCGAGAGACTTGCAAAGTTGCAATGCGCCAGAGCGATGGCGATCGTCGCGTCGAAACGGATTGGTTTCCCCTGCGGCCCCATCCATGTTCTCGCCGATCAATCATTTCCAACTCTCGCTATCAACTCTTTTACCGTCTCCGGCAACGTAAGTTAAATCTCATGTTTCGTTTTCTTTCACTTCTTTTGAAGCTTTTCGTTTGTTTGGTGTTGTTGCAGAGTGAGTGCTCCGAGGTATCAGATCATTCCATTAGGGACAGATCTTAATTGGCTTCTTTTGCTGACTGATTTTCAAGAAAGTTTTTATACATGGCCACCGTGAAGCCTAGGATCATTGGAGGTATGTTCTTTCTCCGTTTCCAATCTTACGATTGTATGCCACTAATAATATTGAAGAATGAACCATTTTGTTAATAATCTTTTATTTATAATTTTTTAAGGTGTGACATGGGTGTGGTGTTTCTCACTTGACAGATATATGTAAAGATCGAATAGGAAGAAATATCAAGCACTTTCTGTCTCGGGTTTAGTGGACTAGGTGATTGCGCCAATTGACATTCTTAAGAAAATAAATGAGATAACCTTACACCAAATCCCTAGGCTTCAATCCATGGCAGGTTCATCGTGTTGGAGAGATTCATTCGTCTTGGTATTCCATGTTTTTTCTTTTAACGCCACTCAGATTTCAGGATCTCCTATCTAACTATTATCGGGTTTTATTTCAGGTCGTGGAGCATGTTTTTGTTCATTTGCCGTTCACTAAGAAATAAGTAGTCACTCCAACAGGTACGAGAGGAGTATGTCTGAGCATTGACATAGTTTATGCAGTTTCTTAGATGCCATGCAGAGTAGTGGAGTTAGCTTATTCAGTTGGTTATAATTTGTTATCTTTTCCAAACCAGGAGCTGTGTATACCGGATTTGATTTTTGCAAGAAACTTTGTGGGTTTCTCAATGATTCGAAGGTGAGGTTTGAAAATACTTTGGCTTAATTTTTTTTTCTCCCACCTATAGTACTCTTGGAAGAGTATATTATTTAGAGAAATTCTCTATAGTTTTTGTCACAAATATAGCCTTTAAGGATCAAAATGACCAAAATATTGTATTAAAGGATGTGTTTTTGGGTTTATGGTTTAGAATTTAGGGTTTAAAGTTTATGATTTAGGGTTTAGAGTTAACGGATGAGGTTTTGGGGGTATGATTTCAAATTTTAAAAACTTAAAAAATATTAAAATTTTCAAAATAAAAAAAAATTATTTTGGTCATTTTATTTTTTTAAGTCTATTTTTGTGACACAAAACTTTAAAAAATCTATTTGAGAGAATTGTCTTATTATTTATGGTTATAAGGTGTGTATGCTTTGTTAGTAGTGAAAGTATAAAGCTTATTGAAAAAATCCTTCCAAATTAGCTTTACCATTATTCTGTCTGTCTTTTTCTTAAATTACATTAATGAACTTTCTGATTTATGGGTCTTGATCATTTGTGTATAAAAATTACTCGTGTGTAATACATATATATATTCTTTCAGGATTCCCTGCTTAAAGTTTTTGAAGTATATGTTTCACAGAAGAAATCAACTTTCTTTTTCAGTGACAATGTGAAAGTGGAATGCTTCTCCGTCACCTATTTCTTCTCTGAAAAACACATCCCCTAGCTCTGCCTTCACGCAAACTTTGTCGTCTCCCGCCGTCCACAATGCTTTCTTTCTCCTCAGTTTCTCTCATTTTGAAGTTCATATGATCACCTAGGTATTAACTTATAAGTATTTGATTGATTAAGATAATTATTCAAGTATTTTTTGCCCATTGTTTATAATCCTTAACAACCAGCATCTATATTGGTCAGTTCAGGTTAAGATAGCTACATTTCACTGTTTAGGATAAGGTTGGATGATCTTTCTGAAGATACTAATGTCTATCATCGGATCTAAAACTCAAAGAAACTTAACATCTTTCTTGATGCTCTTAACAGGGAATCCTCTTTTCCCCGGGAAAAATATAGTCCATCAATTGGATATGATGAATGATCTGTTGGGAACTCCATTTGTGAAACTATTGGAAGGGTCAGTGTCCCTTACCTCTCTCCACAATGCTTACAACAACTGCATTGTTACTTTTCTTGGCTGAACTGCTTTCACTGAATGTGACAGGTGAGGAACGAGAAAGCTGGAAGATACTTGAGGAGCATGAGGTTGAAGAAGTCTATTCGTTTTTCACATAAGCTTCCACATGACGATCCTCTCGATCTTCGTATTCTACAAAAGTTGTTGTCTTTTGAGCTCAATGAACGGCCTACATTTGAAGAGGTGCTTCACAAAATTATTTTACTACATTCCTTATGATCTATTTGGTTGTATTCAACTAAAATTATTGTTTAGGGGTTAGTCCTGACACTTGTGGAGTACTTCAAGGGTGTAGCTAAGAAAGAGACTATATATGAGCTCTCAAAGAGATCCCTCTGTTCAACCTGTCACCAAGCTGGAATTCGAGTTTGAGAGGCTGAAGATCACAAAAGAGGCCATGCCAGAGCTCATATATAGTATCTTGAGACTGCTCTTGAGTACCACCCAAAGATGCTAAAAGAATACTTGGATTTGTGGAATAGAAGATTTTGCTTCATATTAAGTTTTTTTTGTCAAAATTAATATTAATATTAAGTTTTTTGCAGAAGAGAAAAACAAACGTACTACAGTGTTTCTATTACCGGCACTACCCAACAAAAAACATGCTCGAGTTGGTGGTCGGAAGATGAAAGATTTAGGTTTATGAAGAATATGCTTTTTAATGAAGAATATGTTTTCTGTTGCAACATTTAGTTTACACCAAAATAAACAATAGCTTATAAAAATAACTAAATACATAATTTTGTTTTTGGTAGTAGGCAAGTAGCTAGAAAGGAAGTCAGAGAAATGGGACTATGAGTTCATGTCAATAGGTTGTTGTGGTTAGAAGACCATACTCAATCGAAACTTTACATGATTTTGAAATAAATCATTTCACTAATTTTCTCGAAACAATAATGTTATCTCTTGGCAGCTCCATATGATTTCAGCCATTAACTTTGATCTCTTCAGTGTTCTGAGACAATATTACGAACACAGAAAAACAAATTAACGAATATATGAAATCCGTGTTCTTGAGATAATATTAGGAACACAAAAACAAATTAATGAATATAAGAAACCCATTGAATATTAATCTAAAATCAATTCAATCATAACAATTTGCAATGACTGTATATACTTCATAACCTGAAAATTAAATTACGTTAATTGATTTAAATTTCAAACTCTATAAAGTAACTCAAATTCCCAAAATTAGAGACCTCTTTTATTAGTCATCAAAAAGATTCCACCAGTCCCATCTTAAACATTCAATAGGCCAATATTTAAACTAACATAAGAAAGAGATTTTCAAACAAAAACGGCAAATTTATTGCCACAAATTACTCTGAATATATTTAAAATCACAAATAATTAAATTTGTTTATTAAATAAAACCTATACTCAATATAAAAATGAAGATAGTGGTAAAAATTAAAGAGAAACTAAAAGAACATAAAGCAACATATGAAAAACTGCATTTAATAGTTGTATTAATTCCTTAAAAAATGTTGAAGAAAATTAATAAATACACTTAATATCTATCAAAAATATACACTCTCTAAAATTAACTACAGAGAAAACACAAAAATAATCATAGTTTATGTACATATGGAAATTCTGCAATATTCTATAATTAAATAACAAAACTAATTGTAAAATTTTAAAAGCAATAATCCGCGCGAAGCGCGGAAAACGATC     ATTAG   .       PASS    SVTYPE=Deletion;SVLEN=4177      GT      1/1
`
`C09     62451491        DEL26880        TCACAATACTAAAAGCCCTATATGCTGAGATTATAGGCTGCCACGTCACCCAAAATAATCAACCAATAAAAAACAGTTAATCGGACATGTCAGACAGGCCTCCTGTGTTAGTTTCGTCCAGAGTCGAGCATCTGACAATGTGGGCTTCATCCGATAAATTTTCCACTTGGGCTTTGTCTGTTTTTTATATGCGCGGTTGGCCACATAATATATGAATCACCACATTATTTTATGTCAACGTAATTTATGAATCACATTACCTTATGGCAATCTTAATTTATTGAGAATACCTTTCCTCTTCCTTCAAAATGTCGATAGACCTTTGCCCTTTCTCTCACAACTCAAGACTTTTGCCAAGGTGAACAAAGAGAATTCGAGAGACTTGCAAAGTTGCAATGCGCCAGAGCGATGGCGATCGTCGCGTCGAAACGGATTGGTTTCCCCTGCGGCCCCATCCATGTTCTCGCCGATCAATCATTTCCAACTCTCGCTATCAACTCTTTTACCGTCTCCGGCAACGTAAGTTAAATCTCATGTTTCGTTTTCTTTCACTTCTTTTGAAGCTTTTCGTTTGTTTGGTGTTGTTGCAGAGTGAGTGCTCCGAGGTATCAGATCATTCCATTAGGGACAGATCTTAATTGGCTTCTTTTGCTGACTGATTTTCAAGAAAGTTTTTATACATGGCCACCGTGAAGCCTAGGATCATTGGAGGTATGTTCTTTCTCCGTTTCCAATCTTACGATTGTATGCCACTAATAATATTGAAGAATGAACCATTTTGTTAATAATCTTTTATTTATAATTTTTTAAGGTGTGACATGGGTGTGGTGTTTCTCACTTGACAGATATATGTAAAGATCGAATAGGAAGAAATATCAAGCACTTTCTGTCTCGGGTTTAGTGGACTAGGTGATTGCGCCAATTGACATTCTTAAGAAAATAAATGAGATAACCTTACACCAAATCCCTAGGCTTCAATCCATGGCAGGTTCATCGTGTTGGAGAGATTCATTCGTCTTGGTATTCCATGTTTTTTCTTTTAACGCCACTCAGATTTCAGGATCTCCTATCTAACTATTATCGGGTTTTATTTCAGGTCGTGGAGCATGTTTTTGTTCATTTGCCGTTCACTAAGAAATAAGTAGTCACTCCAACAGGTACGAGAGGAGTATGTCTGAGCATTGACATAGTTTATGCAGTTTCTTAGATGCCATGCAGAGTAGTGGAGTTAGCTTATTCAGTTGGTTATAATTTGTTATCTTTTCCAAACCAGGAGCTGTGTATACCGGATTTGATTTTTGCAAGAAACTTTGTGGGTTTCTCAATGATTCGAAGGTGAGGTTTGAAAATACTTTGGCTTAATTTTTTTTTCTCCCACCTATAGTACTCTTGGAAGAGTATATTATTTAGAGAAATTCTCTATAGTTTTTGTCACAAATATAGCCTTTAAGGATCAAAATGACCAAAATATTGTATTAAAGGATGTGTTTTTGGGTTTATGGTTTAGAATTTAGGGTTTAAAGTTTATGATTTAGGGTTTAGAGTTAACGGATGAGGTTTTGGGGGTATGATTTCAAATTTTAAAAACTTAAAAAATATTAAAATTTTCAAAATAAAAAAAAATTATTTTGGTCATTTTATTTTTTTAAGTCTATTTTTGTGACACAAAACTTTAAAAAATCTATTTGAGAGAATTGTCTTATTATTTATGGTTATAAGGTGTGTATGCTTTGTTAGTAGTGAAAGTATAAAGCTTATTGAAAAAATCCTTCCAAATTAGCTTTACCATTATTCTGTCTGTCTTTTTCTTAAATTACATTAATGAACTTTCTGATTTATGGGTCTTGATCATTTGTGTATAAAAATTACTCGTGTGTAATACATATATATATTCTTTCAGGATTCCCTGCTTAAAGTTTTTGAAGTATATGTTTCACAGAAGAAATCAACTTTCTTTTTCAGTGACAATGTGAAAGTGGAATGCTTCTCCGTCACCTATTTCTTCTCTGAAAAACACATCCCCTAGCTCTGCCTTCACGCAAACTTTGTCGTCTCCCGCCGTCCACAATGCTTTCTTTCTCCTCAGTTTCTCTCATTTTGAAGTTCATATGATCACCTAGGTATTAACTTATAAGTATTTGATTGATTAAGATAATTATTCAAGTATTTTTTGCCCATTGTTTATAATCCTTAACAACCAGCATCTATATTGGTCAGTTCAGGTTAAGATAGCTACATTTCACTGTTTAGGATAAGGTTGGATGATCTTTCTGAAGATACTAATGTCTATCATCGGATCTAAAACTCAAAGAAACTTAACATCTTTCTTGATGCTCTTAACAGGGAATCCTCTTTTCCCCGGGAAAAATATAGTCCATCAATTGGATATGATGAATGATCTGTTGGGAACTCCATTTGTGAAACTATTGGAAGGGTCAGTGTCCCTTACCTCTCTCCACAATGCTTACAACAACTGCATTGTTACTTTTCTTGGCTGAACTGCTTTCACTGAATGTGACAGGTGAGGAACGAGAAAGCTGGAAGATACTTGAGGAGCATGAGGTTGAAGAAGTCTATTCGTTTTTCACATAAGCTTCCACATGACGATCCTCTCGATCTTCGTATTCTACAAAAGTTGTTGTCTTTTGAGCTCAATGAACGGCCTACATTTGAAGAGGTGCTTCACAAAATTATTTTACTACATTCCTTATGATCTATTTGGTTGTATTCAACTAAAATTATTGTTTAGGGGTTAGTCCTGACACTTGTGGAGTACTTCAAGGGTGTAGCTAAGAAAGAGACTATATATGAGCTCTCAAAGAGATCCCTCTGTTCAACCTGTCACCAAGCTGGAATTCGAGTTTGAGAGGCTGAAGATCACAAAAGAGGCCATGCCAGAGCTCATATATAGTATCTTGAGACTGCTCTTGAGTACCACCCAAAGATGCTAAAAGAATACTTGGATTTGTGGAATAGAAGATTTTGCTTCATATTAAGTTTTTTTTGTCAAAATTAATATTAATATTAAGTTTTTTGCAGAAGAGAAAAACAAACGTACTACAGTGTTTCTATTACCGGCACTACCCAACAAAAAACATGCTCGAGTTGGTGGTCGGAAGATGAAAGATTTAGGTTTATGAAGAATATGCTTTTTAATGAAGAATATGTTTTCTGTTGCAACATTTAGTTTACACCAAAATAAACAATAGCTTATAAAAATAACTAAATACATAATTTTGTTTTTGGTAGTAGGCAAGTAGCTAGAAAGGAAGTCAGAGAAATGGGACTATGAGTTCATGTCAATAGGTTGTTGTGGTTAGAAGACCATACTCAATCGAAACTTTACATGATTTTGAAATAAATCATTTCACTAATTTTCTCGAAACAATAATGTTATCTCTTGGCAGCTCCATATGATTTCAGCCATTAACTTTGATCTCTTCAGTGTTCTGAGACAATATTACGAACACAGAAAAACAAATTAACGAATATATGAAATCCGTGTTCTTGAGATAATATTAGGAACACAAAAACAAATTAATGAATATAAGAAACCCATTGAATATTAATCTAAAATCAATTCAATCATAACAATTTGCAATGACTGTATATACTTCATAACCTGAAAATTAAATTACGTTAATTGATTTAAATTTCAAACTCTATAAAGTAACTCAAATTCCCAAAATTAGAGACCTCTTTTATTAGTCATCAAAAAGATTCCACCAGTCCCATCTTAAACATTCAATAGGCCAATATTTAAACTAACATAAGAAAGAGATTTTCAAACAAAAACGGCAAATTTATTGCCACAAATTACTCTGAATATATTTAAAATCACAAATAATTAAATTTGTTTATTAAATAAAACCTATACTCAATATAAAAATGAAGATAGTGGTAAAAATTAAAGAGAAACTAAAAGAACATAAAGCAACATATGAAAAACTGCATTTAATAGTTGTATTAATTCCTTAAAAAATGTTGAAGAAAATTAATAAATACACTTAATATCTATCAAAAATATACACTCTCTAAAATTAACTACAGAGAAAACACAAAAATAATCATAGTTTATGTACATATGGAAATTCTGCAATATTCTATAATTAAATAACAAAACTAATTGTAAAATTTTAAAAGCAATAATCCGCGCGAAGCGCGGAAAACGAT      T       .       PASS    SVTYPE=Deletion;SVLEN=4172      GT      1/1
`

**Comment by MariaNattestad** [comment]
I'm not sure I understand your question or what the problem is. Can you elaborate? For instance: What is a reverse chain? Is there something you don't understand? Are you saying you think the outputs of Assemblytics and Syri disagree?

**Comment by jwli-code** [comment]
Genomes are matched in reverse,This is an example
`C09     62451491        62455664        Assemblytics_b_27075    4177    +       Deletion        4173    -4      C09:59463365-59463369:- between_alignments`  
However, this is not recognized in other software such as Syri. Other software will still recognize the mutation, but ALT is just one base.Just like this
`C09     62451491        DEL26880        N      T       .       PASS    END=62455663;ChrB=C09;StartB=59463369;EndB=59463369;Parent=SYN10402;VarType=ShV;DupType=. `

**Comment by jwli-code** [comment]
Assemblytics software results in the location of ALT at C09:59463365-59463369:-.
The ALT sequence of Syri software is C09:59463369-59463369, which is only one bp

**Comment by MariaNattestad** [comment]
The variant in Assemblytics is a between_alignments variant, which just catalogues that there are two alignments whose borders meet at that locus, so you can visualize what's going on with a dot plot perhaps, or Ribbon, or using nucmer's built-in tools if you are curious to see more details.

**Comment by jwli-code** [comment]
Thank you for your prompt reply,I wonder if it has something to do with the fact that I used --mum instead of the maxmatch parameter.

**Comment by MariaNattestad** [comment]
I definitely recommend sticking to the instructions in the README here on github -- they matter a lot for the unique anchor filtering Assemblytics does on the alignments.
