### ISSUE TITLE
Assemblytics web server error

### ISSUE THREAD

**Issue by MehmetGoktay** [MariaNattestad/Assemblytics#7]
Hi Maria,

I have been using assemblytics for a few months for my project. 

I have just wanted to run another nucmer output on webserver but I can not upload any file anymore.

It is the first time that I get this error. 

I have tried with my old nucmer output, it is the same can not upload it. (Error: No file uploaded)

Is there any problem with server?

Best,
Mehmet

**Comment by MariaNattestad** [comment]
Hi Mehmet

Thanks for bringing this up. The web server ran out of space, so now I have deleted some files older than 180 days to make room for new runs. 

Maria

**Comment by lixx3627** [comment]
Hi Maria,

It looks like the web server error of Assemblytics occured again, because I also got the Error: No file uploaded since yesterday. Could you help with that?

Thanks!

Feng

**Comment by MariaNattestad** [comment]
Hi Feng
Sorry about that! I don't have direct access to the server where it's running anymore, but asked Mike Schatz who mentioned the upload folders were full and he emptied them recently, which may be around the same time you got the error. Do you still see this issue?

**Comment by lixx3627** [comment]
Hi Maria,

No worries. The issue is solved and now the assemblytics web server is running. Thanks!

Feng
